# Site settings
title: WebCenter
email: hmjsite@gmail.com
description: "WebCenter Portfolio"
favicon: /img/favicon
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://br.linkedin.com/in/henrique-monteiro-junior-37511651
  - title: facebook
    url: https://facebook.com/monteirojunior
  - title: twitter
    url: https://twitter.com/henryjr1
  - title: mobile
    url: tel:+5598981509791
  - title: envelope
    url: mailto:hmjsite@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: São Luís
  - line: Maranhão, Brasil

# Build settings
markdown: kramdown
permalink: pretty
